S02 loading
WildCodeSchool/2023-02-js-btz-apollo pull request #33
Opened 2023-04-27 09:16 UTC by xFokko

2023-04-27 09:17 UTC, Ptbambie approved these changes

2023-04-27 13:39 UTC, CedricPerot approved these changes

2023-04-27 13:45 UTC, piveteauit requested changes

2023-04-27 13:45 UTC, piveteauit commented on src/pages/Scene.jsx
> +              {objects &&
{objects &&
                objects
                  .map((qqch) => {
                     if (Star) return <Sun key={qqch.id} sun={qqch} />
                     if (Planet) return <Planet key={qqch.id} planet={qqch} />
                     
                     return null
                  })}

2023-04-27 14:01 UTC, xFokko commented on src/pages/Scene.jsx
> +              {objects &&
c'est good
👌🥙

2023-04-28 06:58 UTC, piveteauit approved these changes

2023-04-28 06:58 UTC, merged